### ISSUE TITLE
Offline version?

### ISSUE THREAD

**Issue by gforcada** [wimglenn/johnnydep#107]
Imagine a package that has lots of dependencies (say [Plone](https://pypi.org/project/Plone/), as of `pip install Plone==6.0.0` that amounts to __243__ dependencies).

During the testing phase of that package and all other tooling run on it, one wants to also print a (maybe not so useful because of the size 😅 ) graph of all its dependencies.

Given that the package is already installed and its dependencies are locally available, could it be possible to reuse the locally available sdists/wheels to extract the information? 🤔 

That would massively speed up the dependencies tree generation 🚀 

Maybe by passing a lock-file (i.e. a file that already has pinned all the dependencies) and only warn/error if a dependency is not found there, and only for those ones reach to pypi, would be also a major speed up. _Maybe a separate issue might be useful here_.

I'm part of the @plone organization and we are trying to re-architecture the project, try to get rid of circular dependencies, see where we have to cut the dependencies to remove some old packages, etc etc.

For that, having a reliable tool to get the dependencies is fundamental.

**Comment by wimglenn** [comment]
I'd considered this a while ago, but there were a few blockers - some of the fields that johnnydep offers can not be easily discovered for an already-installed package. A couple of examples are the checksum and the download link, which need a release artifact such as a .whl or a .tar.gz. I'm also not sure how trustworthy the locally available metadata might be - for example for editable installs of some "work in progress".

**Comment by gforcada** [comment]
Fair points 👍🏾 thanks for taking the time to answer! 😄 

I would be ok with closing the issue, if you don't see it being feasible to implement.

**Comment by Archmonger** [comment]
I do still think there is an argument for local inspection.

For static, non-development environments it would be _significantly_ faster to parse locally.

Given that legacy eggs are easy to parse through, the main complexity would be parsing local wheels.

```python
# One liner to parse eggs
names = pkg_resources.get_distribution("my_pkg_name").get_metadata("top_level.txt").splitlines()
```

I'm not entirely sure what the best way of parsing wheels would be though. For example `django-jazzmin` does not contain a `top_level.txt`, but does export `jazzmin`. Perhaps it would involve introspection into `RECORD` metadata?
