### ISSUE TITLE
Generate dependencies out of a requirements.txt / lock-file

### ISSUE THREAD

**Issue by gforcada** [wimglenn/johnnydep#108]
See #107 for the rationale, the TL;DR; is:

It would be great to be able to pass a `requirements.txt` file pinned versions, so no resolution might be needed from `johnnydep` and thus speed up the dependencies listing.

At the same time, if a package does depend on another package that is not on `requirements.txt` it could warn about it ✨ 

Does that make sense? 🤔

**Comment by wimglenn** [comment]
It makes sense, but I think it's out of scope for johnnydep, and pip itself already provides some of that functionality: you can `pip install --no-deps -r requirements.txt` and then `pip check` to make sure all the transitive dependencies are met.

**Comment by gforcada** [comment]
Fair point.
