### ISSUE TITLE
Work with editable projects

### ISSUE THREAD

**Issue by gforcada** [wimglenn/johnnydep#109]
One can `pip install -e .`, i.e. set a local source tree to be installed by `pip` so it is available to work with it.

It would be great if `johnnydep` could also work with this projects and extract their dependencies list.

This means that if I have +200 local projects (see #107 😄 ) and I'm adjusting their dependencies (maybe using [z3c.dependencychecker](https://pypi.org/project/z3c.dependencychecker/) to get the dependencies not listed) I can keep iterating with these two tools (`johnnydep` and `z3c.dependencychecker`) to fix and double check if the dependency tree is being adjusted as I work, not only after all of it is released.

Specially with trying to get rid of old dependencies (`six` for py3+ only packages, etc) would be really useful to have the development version of the dependencies, specially if they are generated via CI.

**Comment by wimglenn** [comment]
Unfortunately, the _metadata_ for an editable installation is not reliable - try it yourself, you can edit the dependencies in `setup.py` or `pyproject.toml` and the info such as [`importlib.metadata.requires`](https://docs.python.org/3/library/importlib.metadata.html#distribution-requirements) will still remain 'stale' until the editable installation step is repeated (when the metadata gets regenerated). So the only way to get the correct metadata is to repeat an installation, which johnnydep would rather not do directly (`setup.py` execution). Unfortunately I think that kills the idea, until such a time as all projects declare their dependencies statically, which will probably never happen :(

**Comment by gforcada** [comment]
Right, but it could print a message, as `z3c.dependencychecker` is doing, that information might be stale until you run yourself `python setup.py develop` again.

Thanks for taking the time to answer.
