### ISSUE TITLE
Create a GitHub Action?

### ISSUE THREAD

**Issue by gforcada** [wimglenn/johnnydep#110]
While writing #107 #108 #109 it come to me, specially with #109 in mind, that it would be great to have `johnnydep` as a GitHub Action 🎉 

An action that takes:
- a project name, or
- a requirements.txt (if #108 ), or
- it defaults (if #109) to the package where the action is run (I guess there has to be a variable somewhere that gives you that information)

One could also select which output format one wishes for.

With this, it generates the dependency list and stores it on CI for later inspection or manual comparison between different runs ✨

**Comment by wimglenn** [comment]
If you're working in an otherwise empty venv, then simply installing the package is also generating the dependency list (all transitive deps will be listed in `pip freeze` after your installation). That seems much simpler than attempting to generate it without an installation?

**Comment by wimglenn** [comment]
You may be interested in the [pipdeptree](https://github.com/tox-dev/pipdeptree) project, which is similar to johnnydep but works with the set of currently installed packages to generate a graph.

See the example in the README: [Is it possible to find out why a particular package is installed?](https://github.com/tox-dev/pipdeptree#is-it-possible-to-find-out-why-a-particular-package-is-installed)

**Comment by gforcada** [comment]
Yes, I saw it, and a few others: `pipgrip`, `pydeps` etc 😄
