### ISSUE TITLE
Question: Do i need to configure JohnnyDist class to handle private index?

### ISSUE THREAD

**Issue by wil-den** [wimglenn/johnnydep#142]
Our private index sits on a gitlab server with custom ssl certs. I have configured pip locally to handle my requests when publishing to and installing from the gitlab package registry.
So my question is, will `requests` use the same config or will I have to configure it again to be able to connect to our gitlab package registry?

Thanks in advance.

**Comment by wil-den** [comment]
You can ignore this. Worked like a charm right out of the box

**Comment by wimglenn** [comment]
Johnnydep 1.x uses pip subprocesses, so it will respect pip's configuration. Johnnydep 2.x, which is not yet released, removes this dependency (#140). I have not decided yet whether it will load from pip's configuration files / env variables, or just require the user to specify the index configuration explicitly, but I'm leaning towards the latter.

Note that Johnnydep does not use `requests`.
