### ISSUE TITLE
Can't specify pip's "--extra-index-url" flag

### ISSUE THREAD

**Issue by genebean** [wimglenn/johnnydep#32]
Can you please add a parameter to allow passing this flag? Some packages are stored on our internal repository but we still pull deps from the public index.

**Comment by wimglenn** [comment]
@genebean  Try [v0.8](https://github.com/wimglenn/johnnydep/releases/tag/v0.8) put to PyPI

**Comment by genebean** [comment]
Thanks! I'll give it a try Monday
