### ISSUE TITLE
Johnnydep builds wheel file

### ISSUE THREAD

**Issue by sbliven** [wimglenn/johnnydep#53]
I'm trying to get the dependencies for a package that depends on wxPython==4.0.4. I was surprised that johnnydep tries to build the wheel files. Is this really necessary? It fails to build in my environment for some reason. I could probably fix whatever the problem is, but one of the reasons I was interested in johnnydep was to check dependencies _without_ building anything.

**Comment by wimglenn** [comment]
Unfortunately it is necessary in the general case, there is currently no reliable way to get dependencies from a source distribution without executing the build.  For details about that:

https://discuss.python.org/t/why-isnt-source-distribution-metadata-trustworthy-can-we-make-it-so/2620/8

https://discuss.python.org/t/standardized-way-for-receiving-dependencies/3821

You can either install the build dependencies, or bug the project maintainers to publish wheel distributions for your platform.

**Comment by sbliven** [comment]
Ok, that is a good compromise. Thanks for explaining.

**Comment by sbliven** [comment]
If #54 gets implemented, maybe you could add an option to skip building completely (and just prune that branch of the tree. Not all dependencies will be exactly correct, but for my purposes a quick overview is preferable to a slow but thorough pass.
