### ISSUE TITLE
questions regarding "pinned", feature request

### ISSUE THREAD

**Issue by mathog** [wimglenn/johnnydep#55]
When johnnydep is run like:

`johnnydep --output-format pinned scanpy
`

after the "[info]" section it emits this:

```
scanpy==1.5.1
anndata==0.7.3
h5py==2.10.0
importlib-metadata==1.6.1
joblib==0.15.1
legacy-api-wrap==1.2
matplotlib==3.2.2
etc.
```

Is that the highest version for each within the intersection of version restrictions?

If there was a problem where the version restrictions did not overlap, what would it emit in this list section?  Would there be error messages of some type?  (Hopefully this is never encountered, but I need to know so that the code processing this output handles it correctly.)

Could we have a switch to dispense with the display of the [info] section?  The only output desired in the context of some present work is the list of names and version numbers.

Thanks.

**Comment by wimglenn** [comment]
> Is that the highest version for each within the intersection of version restrictions?

Yes.

>  If there was a problem where the version restrictions did not overlap, what would it emit in this list section?

It would not be able to emit this section in the first place. It should error out with an unhandled exception.
