### ISSUE TITLE
Can it resolve version requirements?

### ISSUE THREAD

**Issue by magiblot** [wimglenn/johnnydep#56]
Hi,

I am trying to obtain, for every package in a `requirements.txt` file:
1. The exact resolved version, as if I was running `pip install -r requirements.txt`.
2. The import names.

I know that johnnydep can easily figure out import names, but can it resolve package versions given version requirements?

I could run `pip download -r requirements.txt`, but since johnnydep is already downloading packages, I'd prefer not to do it twice to reduce execution time.

Thanks!

**Comment by wimglenn** [comment]
This project will display dependency tree for a single package. There is no support for `requirements.txt`. If you want that, suggest you install in a temporary environment, and then use `pip list --format=freeze`.  Hope this helps!
