### ISSUE TITLE
Option to only show direct dependencies

### ISSUE THREAD

**Issue by lazka** [wimglenn/johnnydep#64]
Is there a way to output only direct dependencies?

The relation seems to be shown in the debug output, but the output format contains all dependencies recursively without a way to tell them apart.

Or does anyone know another tool that provides this?

For context: I'd like to verify dependencies for Linux/Windows distro Python packages.

thanks!

**Comment by lazka** [comment]
ah, it can be done in python:

```python
def get_deps(name):
    from johnnydep import JohnnyDist
    return [d.name for d in JohnnyDist(name).children]

```

**Comment by wimglenn** [comment]
@lazka  Direct dependencies are the "requires" field, for example on CLI:

```
$ johnnydep boto3 --fields name requires -o yaml --no-deps
- name: boto3
  requires:
  - botocore<1.21.0,>=1.20.53
  - jmespath<1.0.0,>=0.7.1
  - s3transfer<0.4.0,>=0.3.0
```

or in Python:

```
>>> JohnnyDist("boto3").requires
['botocore<1.21.0,>=1.20.53',
 'jmespath<1.0.0,>=0.7.1',
 's3transfer<0.4.0,>=0.3.0']
```

**Comment by lazka** [comment]
Thank you!
