### ISSUE TITLE
Misleading output with `--output-format pinned`

### ISSUE THREAD

**Issue by kokkonisd** [wimglenn/johnnydep#66]
I'm expecting `--output-format pinned` to attempt to resolve the dependency tree, keeping any consistent requirements across different dependencies. However, if I'm not mistaken, when it finds a common dependency it just defaults to fetching the latest version.
For example, many of `scancode-toolkit`'s dependencies depend on `Beautifulsoup4<5.0.0,>=4.0.0`; yet, when running `johnnydep scancode-toolkit --output-format pinned`, we get `beautifulsoup4==4.9.3`, when it should be `beautifoulsoup4<5.0.0,>=4.0.0`.

**Comment by wimglenn** [comment]
Working as intended.

Output format pinned is for pinning (a deployment) to an _exact_ version.  The specifier `<5.0.0,>=4.0.0` is not a pin, that's still a range of possible versions. `--output-format` will choose the latest version which satisfies each specifier across the entire tree, and for this case 4.9.3 is the correct result.
