### ISSUE TITLE
systemd crashes jonnydep

### ISSUE THREAD

**Issue by awinner1** [wimglenn/johnnydep#70]
Crash dump follows:

$johnnydep systemd
2021-09-16 20:59:09 [info     ] init johnnydist                [johnnydep.lib] dist=systemd parent=None
2021-09-16 20:59:11 [warning  ] Created temporary directory: /tmp/pip-ephem-wheel-cache-vl7dl_2t
Created temporary directory: /tmp/pip-req-tracker-7zfi3jqu
Initialized build tracking at /tmp/pip-req-tracker-7zfi3jqu
Created build tracker: /tmp/pip-req-tracker-7zfi3jqu
Entered build tracker: /tmp/pip-req-tracker-7zfi3jqu
Created temporary directory: /tmp/pip-wheel-e4nri3uh
1 location(s) to search for versions of systemd:
* https://pypi.org/simple/systemd/
Fetching project page and analyzing links: https://pypi.org/simple/systemd/
Getting page https://pypi.org/simple/systemd/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/systemd/ HTTP/1.1" 200 2932
  Found link https://files.pythonhosted.org/packages/d7/93/b0e60edab91f32e7375d4c6af6f932c56fe739cdb02cadc40034d8be4698/systemd-0.8.0.tar.gz#sha256=c24a148ffd069d0a90ab28ca47883973b2ffad218a6ecf2c6dcb40403eca4b6d (from https://pypi.org/simple/systemd/), version: 0.8.0
  Found link https://files.pythonhosted.org/packages/05/9c/e29a9c3d06ef612317d517e456e3877eba355e884ebaaa71a59eeb4b648a/systemd-0.8.1.tar.gz#sha256=92c046d2fc81f5a13835cd8805a0011e0ec00779d79f84fc232f82935a750a42 (from https://pypi.org/simple/systemd/), version: 0.8.1
  Found link https://files.pythonhosted.org/packages/52/bb/78a742430946205487ff36f00e721141ba462646f2cae989e1d8fe07b5b7/systemd-0.8.2.tar.gz#sha256=bf3e18fa9fc85f7a05b3d26ffb9d1e046a15f5acbe53e56476d65f0d4dbf95fd (from https://pypi.org/simple/systemd/), version: 0.8.2
  Found link https://files.pythonhosted.org/packages/ba/94/ec245e71c04e448b02c88a4b98ad0533792a2f83b78222dd723453ca7d50/systemd-0.8.3.tar.gz#sha256=8fc2d654d86023b29e8460a7c763e23a69f759e19553a7443b12f374de601229 (from https://pypi.org/simple/systemd/), version: 0.8.3
  Found link https://files.pythonhosted.org/packages/e0/cc/5473d2b53e35d138e3fe242720dfe541c33e3853643a4067c98e519d998a/systemd-0.8.4.tar.gz#sha256=cd186d6a996dc9c39e233fbaabb0c9b7a8223d739592412721edb5383b10b22f (from https://pypi.org/simple/systemd/), version: 0.8.4
  Found link https://files.pythonhosted.org/packages/ed/de/c21a32497cde8c13d5b4baedb9835deb6cbbcc2bc350ae13487eadc09bbe/systemd-0.8.5.tar.gz#sha256=754dc0ba7f7f6009b620d2c8a82f062184ef12d2adc8588d511bc8c479b37e6b (from https://pypi.org/simple/systemd/), version: 0.8.5
  Found link https://files.pythonhosted.org/packages/03/b4/8fe6cb41897476d10985ca86a285b58296a93258f246e1a2244463901ac7/systemd-0.8.7.tar.gz#sha256=3456c5638d6051b012be4cbe85daf45957219dd039032f30d830b5b55c0071c1 (from https://pypi.org/simple/systemd/), version: 0.8.7
  Found link https://files.pythonhosted.org/packages/8a/a4/45f60d0e392bdfc7d4c4c6544b4ec0f29f567803dfe63eecca32a1690ea0/systemd-0.8.8.tar.gz#sha256=41f44aac62c4a4519f7174559a9fa62b1165d7523292ebe0f59da8381eafe16b (from https://pypi.org/simple/systemd/), version: 0.8.8
  Found link https://files.pythonhosted.org/packages/00/60/7807c9cfa0d2b2a3837c86849c49d8020768be0909324abe358a27e6017a/systemd-0.8.9.tar.gz#sha256=599a720ddbf68775439170ebfaae8c0e53adb1535594a9e23e20f4a1e7ab6a55 (from https://pypi.org/simple/systemd/), version: 0.8.9
  Found link https://files.pythonhosted.org/packages/a3/5e/88616144f0cda81a3963ee694a951a6fcf2a23cc4d36f57b3b067ea9eda8/systemd-0.9.0.tar.gz#sha256=aa85e16632b421e6a5472ece861f663607aca53cecd96403e8f1b669597e18ce (from https://pypi.org/simple/systemd/), version: 0.9.0
  Found link https://files.pythonhosted.org/packages/2a/1d/0ee795259c4d9742cb6e33dd2535c57f3d4510e1a2e89e07095c5d52809f/systemd-0.9.1.tar.gz#sha256=6f2cea10d4780afb3c98c71f572fe74e2d258dde7d035f78343d66112613893c (from https://pypi.org/simple/systemd/), version: 0.9.1
  Found link https://files.pythonhosted.org/packages/0c/10/b5e0a27355d061a0d990eca9179346d9775bde56d63e6b486c3f3e7827e5/systemd-0.9.2.tar.gz#sha256=88070309662488204cffdd1a0940af3b0c0f7f95fd277c6bb1aa410d40ba6c8b (from https://pypi.org/simple/systemd/), version: 0.9.2
  Found link https://files.pythonhosted.org/packages/c5/71/3688bcc1eff600245cfbf369c07013f2a02b7b520bc17e45a28f3a5f571f/systemd-0.9.3.tar.gz#sha256=fda7ed021ca4f238bd9aa81b1585945f8dd260cda4d0bcef93c68067804a78eb (from https://pypi.org/simple/systemd/), version: 0.9.3
  Found link https://files.pythonhosted.org/packages/9c/d7/e9580dc1d36326339742b027f686bae280762de479282f17cecf5f5dc3e1/systemd-0.9.4.tar.gz#sha256=0301453f8c7dfb861519756a4806782c3afda4b41266a769bd55ab0c0ebd96ab (from https://pypi.org/simple/systemd/), version: 0.9.4
  Found link https://files.pythonhosted.org/packages/38/f3/f86c3e99d269f2faaf3df24d042fa20ec677844c238826a7f5b79fcdaa31/systemd-0.9.5.tar.gz#sha256=50524db64417f79c33f87700bd1108841ee153bcacae4e04fd4344eabb6456b9 (from https://pypi.org/simple/systemd/), version: 0.9.5
  Found link https://files.pythonhosted.org/packages/7b/cf/500788fa7f90bab9b536ee3a792b6fa8712a2badff32fe44335b9c24c13c/systemd-0.9.6.tar.gz#sha256=e0d5d7963d910e13b204b856fe073e5314a35deee61c972b015c588ea72303c8 (from https://pypi.org/simple/systemd/), version: 0.9.6
  Found link https://files.pythonhosted.org/packages/68/40/f996e523567e43af5fd4d039875bf0d0090767f6e485abf2120010ae81a3/systemd-0.9.7.tar.gz#sha256=eee747f7f53896136a347e0235b8af23aa10a16893ff471add733306eca011c9 (from https://pypi.org/simple/systemd/), version: 0.9.7
  Found link https://files.pythonhosted.org/packages/b7/a6/6f8c3e16cbbe261fe56e57500992c980a48e94e133a0813465a39f74a1e6/systemd-0.9.8.tar.gz#sha256=06da49b059c7427179c0594dc303d1fc6b781ba6696199022120ab229a5fa612 (from https://pypi.org/simple/systemd/), version: 0.9.8
  Found link https://files.pythonhosted.org/packages/89/96/2ec26001fa405d03ec36387d9e0f527367f645264806d2c2687a69adf5a5/systemd-0.9.9.tar.gz#sha256=3eaba84ff296514dd94384711ebdff23f5a143b4fb654e91fee8140bf63999f2 (from https://pypi.org/simple/systemd/), version: 0.9.9
  Found link https://files.pythonhosted.org/packages/ea/45/ca2b7f6a38ee636147e1463309bc2062a354fd6c19f44b37795f192a932b/systemd-0.9.15.tar.gz#sha256=be2ad38075cc910f57fb0945b6f58f697b99e974ab6248ecf33886d74adc7aa0 (from https://pypi.org/simple/systemd/), version: 0.9.15
  Found link https://files.pythonhosted.org/packages/92/be/b0e7a95a1710f5cc4fa4873a294eebd4557be40a6e7f1313e5430bd70725/systemd-0.10.0.tar.gz#sha256=9f2b556464c2a68100094fcaf72db40bf0b5d966438e92373d02399ea4dae364 (from https://pypi.org/simple/systemd/), version: 0.10.0
  Found link https://files.pythonhosted.org/packages/1d/ff/f200200791f04510a469f031635b1c462c109c2f4f7ed3672576543a38ab/systemd-0.11.0.tar.gz#sha256=8de9889cfdcad462584fcaaf24618eac06ab3849cd4874ee1b98a47426af9648 (from https://pypi.org/simple/systemd/), version: 0.11.0
  Found link https://files.pythonhosted.org/packages/e1/b4/8a549a683a5b79957b09bc9a9cfcc493abe54424c8a871088cd392b89909/systemd-0.11.1.tar.gz#sha256=e9a50879ab6bf5351fd2f10913cb939be9239587800404f5b171b19b39ae5c1d (from https://pypi.org/simple/systemd/), version: 0.11.1
  Found link https://files.pythonhosted.org/packages/b7/44/878033fc79463c609ea6633f5c086a34caf4ea9ad9a01a3173873a5c2904/systemd-0.12b0.tar.gz#sha256=76dc03275847064c93591ef7e22e294ee89ea416bf674465fe86431365addad7 (from https://pypi.org/simple/systemd/), version: 0.12b0
  Found link https://files.pythonhosted.org/packages/61/b0/7af5b9e068503b88c1127975d28ae90062a6afe6ef3e5a85c9be929c0f60/systemd-0.12.0.tar.gz#sha256=bf60af358e2a849e82691ec0b9a4a4dfbeba0412598ecdb07b91ff57118bf275 (from https://pypi.org/simple/systemd/), version: 0.12.0
  Found link https://files.pythonhosted.org/packages/83/8d/73936d8ffaed466b2debf42b20225584da5ed99976a5739b52a06aeef3ef/systemd-0.13.0.tar.gz#sha256=dc5b5bf5d721198fbfbcd9b7b0c006155948f998162aeeecbaad2646cce4dfa6 (from https://pypi.org/simple/systemd/), version: 0.13.0
  Found link https://files.pythonhosted.org/packages/1f/63/a816e28c623cf21cf882d36017a115bb14c5f85261e704e1ee29d3b3db92/systemd-0.14.0.tar.gz#sha256=ee9797bb33b7838dcb00f1c64d837a0b6506f1a9b3550093aadb8088cd725329 (from https://pypi.org/simple/systemd/), version: 0.14.0
  Found link https://files.pythonhosted.org/packages/ec/3b/93b0d6d24f7c124aaf978771d4921e96ee4195cc0d25cc26f460e871ab42/systemd-0.15.0.tar.gz#sha256=c5224003c25a4e8ab5b8ebf0a40400ecb8ed51764e932e37b5e38e959d69be6d (from https://pypi.org/simple/systemd/), version: 0.15.0
  Found link https://files.pythonhosted.org/packages/d2/27/f7091d2341943891e459bf752d863bad6ec76598d1f201d3e9714e9d855a/systemd-0.15.1.tar.gz#sha256=39b5a9ecda177cf5cc42b06af68adfb4acaf065aea43008ddb95546d510dcca1 (from https://pypi.org/simple/systemd/), version: 0.15.1
  Found link https://files.pythonhosted.org/packages/d4/c2/2195b049effd866b5d26926e672be83fc6f3263aa71ea0639e8eab44851e/systemd-0.16.1.tar.gz#sha256=f44a02434cb1e6ff686bc7d25a7a665cc7af665965e933df3e76fa02d351a75b (from https://pypi.org/simple/systemd/), version: 0.16.1
Given no hashes to check 29 links for project 'systemd': discarding no candidates
Using version 0.16.1 (newest of versions: 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.15, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.15.1, 0.16.1)
Collecting systemd
  Created temporary directory: /tmp/pip-unpack-kb7fsedw
  Getting credentials from keyring for files.pythonhosted.org
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/d4/c2/2195b049effd866b5d26926e672be83fc6f3263aa71ea0639e8eab44851e/systemd-0.16.1.tar.gz HTTP/1.1" 200 173569
  Downloading systemd-0.16.1.tar.gz (173 kB)
  Added systemd from https://files.pythonhosted.org/packages/d4/c2/2195b049effd866b5d26926e672be83fc6f3263aa71ea0639e8eab44851e/systemd-0.16.1.tar.gz#sha256=f44a02434cb1e6ff686bc7d25a7a665cc7af665965e933df3e76fa02d351a75b to build tracker '/tmp/pip-req-tracker-7zfi3jqu'
    Running setup.py (path:/tmp/pip-wheel-e4nri3uh/systemd/setup.py) egg_info for package systemd
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info
    writing /tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/requires.txt
    writing top-level names to /tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/top_level.txt
    writing manifest file '/tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'build_requires'
      warnings.warn(msg)
    warning: no previously-included files matching '*' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'systemd'
    warning: no previously-included files matching '*' found under directory '__pycache__'
    warning: no previously-included files found matching '.*'
    warning: no files found matching 'README.md'
    writing manifest file '/tmp/pip-wheel-e4nri3uh/systemd/pip-egg-info/systemd.egg-info/SOURCES.txt'
  Source in /tmp/pip-wheel-e4nri3uh/systemd has version 0.16.1, which satisfies requirement systemd from https://files.pythonhosted.org/packages/d4/c2/2195b049effd866b5d26926e672be83fc6f3263aa71ea0639e8eab44851e/systemd-0.16.1.tar.gz#sha256=f44a02434cb1e6ff686bc7d25a7a665cc7af665965e933df3e76fa02d351a75b
  Removed systemd from https://files.pythonhosted.org/packages/d4/c2/2195b049effd866b5d26926e672be83fc6f3263aa71ea0639e8eab44851e/systemd-0.16.1.tar.gz#sha256=f44a02434cb1e6ff686bc7d25a7a665cc7af665965e933df3e76fa02d351a75b from build tracker '/tmp/pip-req-tracker-7zfi3jqu'
Building wheels for collected packages: systemd
  Created temporary directory: /tmp/pip-wheel-n6lgxcra
  Building wheel for systemd (setup.py): started
  Destination directory: /tmp/pip-wheel-n6lgxcra
  Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-e4nri3uh/systemd/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-e4nri3uh/systemd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n6lgxcra
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'build_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/systemd
  copying systemd/journal.py -> build/lib.linux-x86_64-3.8/systemd
  copying systemd/daemon.py -> build/lib.linux-x86_64-3.8/systemd
  copying systemd/__init__.py -> build/lib.linux-x86_64-3.8/systemd
  running build_ext
  building 'systemd._daemon' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/systemd
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c systemd/_daemon.c -o build/temp.linux-x86_64-3.8/systemd/_daemon.o
  systemd/_daemon.c:539:10: fatal error: systemd/sd-daemon.h: No such file or directory
    539 | #include <systemd/sd-daemon.h>
        |          ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  Building wheel for systemd (setup.py): finished with status 'error'
  ERROR: Failed building wheel for systemd
  Running setup.py clean for systemd
  Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-e4nri3uh/systemd/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-e4nri3uh/systemd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'build_requires'
    warnings.warn(msg)
  running clean
  removing 'build/temp.linux-x86_64-3.8' (and everything under it)
  removing 'build/lib.linux-x86_64-3.8' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.8' does not exist -- can't clean it
  removing 'build'
Failed to build systemd
Cleaning up...
  Removing source in /tmp/pip-wheel-e4nri3uh/systemd
Removed build tracker: '/tmp/pip-req-tracker-7zfi3jqu'
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/wheel.py", line 188, in run
    raise CommandError(
pip._internal.exceptions.CommandError: Failed to build one or more wheels
 [johnnydep.pipper]
Traceback (most recent call last):
  File "/home/anthony/.local/bin/johnnydep", line 8, in <module>
    sys.exit(main())
  File "/home/anthony/.local/lib/python3.8/site-packages/johnnydep/cli.py", line 77, in main
    dist = JohnnyDist(
  File "/home/anthony/.local/lib/python3.8/site-packages/johnnydep/lib.py", line 64, in __init__
    self.import_names, self.metadata = _get_info(
  File "/home/anthony/.local/lib/python3.8/site-packages/cachetools/func.py", line 66, in wrapper
    v = func(*args, **kwargs)
  File "/home/anthony/.local/lib/python3.8/site-packages/johnnydep/lib.py", line 392, in _get_info
    data = pipper.get(
  File "/home/anthony/.local/lib/python3.8/site-packages/cachetools/decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "/home/anthony/.local/lib/python3.8/site-packages/johnnydep/pipper.py", line 143, in get
    out = subprocess.check_output(args, stderr=subprocess.STDOUT, cwd=scratch_dir)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-vvv', '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--progress-bar=off', 'systemd']' returned non-zero exit status 1.

**Comment by awinner1** [comment]
note after installing the required libs for systemd module "sudo apt install pkg-config libsystemd-dev" it does not crash anymore, but it still does not give any dependencies. only output is : 

name     summary
-------  ----------------------
systemd  Python systemd wrapper

**Comment by wimglenn** [comment]
For systemd metadata 
 https://github.com/mosquito/cysystemd/blob/c0d5f3b919c4876360f15ad1179f113731b8a301/setup.py#L55-L93 
 the `install_requires` is not used, i.e. this project doesn't specify any Python dependencies.

The build failing without systemd headers is expected, the same would have happened with a pip install since this project is not publishing any wheels, only a source distribution.  That's mentioned on their landing page: https://pypi.org/project/systemd/ 

So, I'm not convinced johnnydep's output has anything wrong here - what is the expected output?

**Comment by wimglenn** [comment]
Closing due to 2 weeks with no answer.  Feel free to reopen...
