### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by davystrong** [wimglenn/johnnydep#82]
I'm getting an error when trying to build the dependencies for ```azureml-pipeline``` (with ```johnnydep --output-format pinned --ignore-errors azureml-pipeline```):
```
Traceback (most recent call last):
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/bin/johnnydep", line 8, in <module>
    sys.exit(main())
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/johnnydep/cli.py", line 90, in main
    print(dist.serialise(fields=args.fields, format=args.output_format, recurse=args.recurse))
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/johnnydep/lib.py", line 260, in serialise
    data += [d for dep in deps for d in dep.serialise(fields=fields, recurse=False)]
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/johnnydep/lib.py", line 260, in <listcomp>
    data += [d for dep in deps for d in dep.serialise(fields=fields, recurse=False)]
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/johnnydep/lib.py", line 326, in flatten_deps
    if dist.version_latest_in_spec in spec and set(dist.extras_requested) >= extras:
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 782, in __contains__
    return self.contains(item)
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 789, in contains
    item = parse(item)
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/azure-pipelines-w6oS6jRb-py3.8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
It was well into the process, as it had already started printing a list of resolved dependencies. I imagine it's a problem with the ```azure-pipelines``` package (I've had quite a bit of trouble with it already), but it would be good if the --ignore-errors option was able to ignore this. I'm on an M1 Mac if that makes any difference.

**Comment by wimglenn** [comment]
Hi @davystrong , what pip version is installed? Can you please advise what output you see for `pip install azureml-train-automl-client==` ?

**Comment by davystrong** [comment]
Hello @wimglenn, thanks for getting back! My Python version is 3.8.12 (installed using pyenv) and pip is 22.0.4. The output you requested was
```
ERROR: Could not find a version that satisfies the requirement azureml-train-automl-client== (from versions: 1.0rc83, 1.0rc85, 1.0.76, 1.0.79, 1.0.81, 1.0.81.1, 1.0.83, 1.0.85, 1.0.85.1, 1.0.85.2, 1.0.85.3, 1.0.85.4, 1.1.0rc0, 1.1.1rc0, 1.1.2rc0, 1.1.5, 1.1.5.1, 1.1.5.2, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.0.post1, 1.6.0, 1.6.0.post1, 1.7.0, 1.7.0.post1, 1.8.0, 1.9.0, 1.9.0.post1, 1.10.0, 1.11.0, 1.11.0.post1, 1.12.0, 1.12.0.post1, 1.12.0.post2, 1.13.0, 1.13.0.post1, 1.13.0.post2, 1.14.0, 1.14.0.post1, 1.15.0, 1.15.0.post1, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.0.post1, 1.23.0, 1.23.0.post1, 1.24.0, 1.25.0, 1.26.0, 1.27.0, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.0, 1.33.0, 1.34.0, 1.35.0, 1.36.0, 1.37.0, 1.38.0, 1.38.0.post2, 1.38.0.post3, 1.39.0)
ERROR: No matching distribution found for azureml-train-automl-client==
```

One other point, I since worked through the dependencies manually to see which ones were broken: the package depends on `pyarrow`, which doesn't have a Wheel for ARM64 and failed to compile, and `azureml-dataprep-native`, `azureml-dataprep-rslex` and `dotnetcore2`, which don't have wheels available for M1 and don't have source.

I also narrowed it down to a specific subdependency, `azureml-dataprep`. If I run `johnnydep...` on this, I get the same error. However, if I run it for each of `azureml-dataprep`'s dependencies, I get errors (since the dependencies aren't compatible with M1) which are ignored because of --ignore-errors, but I don't get the `TypeError: expected string or bytes-like object` error. Hope this helps.

**Comment by wimglenn** [comment]
Yes, that helps. I was on Python-3.10 so saw different errors, but I guess a `pip install -v azureml-dataprep` on Python 3.8 will start to go crazy (backtracking and downloading older and older releases, attempting to find a solution).

The `TypeError` in johnnydep comes from [here](https://github.com/wimglenn/johnnydep/blob/v1.11/johnnydep/lib.py#L326), because at this stage there is no version in spec and checking if `None` is in a specifier set is not allowed. In a future version I'll make a more useful error message there, explaining why a solution was not found.

**Comment by davystrong** [comment]
Sorry for the delay getting back! A more descriptive error message would be good, but what I was looking for was some way of viewing all recursive dependencies for a package, so I could just install them all with `--no-deps`. This was specifically so I could install all dependencies for a broken package and then try to fix it (that's why I used `--ignore-errors`). Would it be possible to warn about this error but ignore it too, so I could at least install the rest of the packages? I imagine this could cause conflicts if the broken package depended on a different version of a different package, but for me at least that would be preferable.

**Comment by wimglenn** [comment]
That's not really possible in general, because the dependencies specified by a package can be conditional upon the python version among other things (see [environment markers](https://peps.python.org/pep-0508/#environment-markers) in PEP 508). If we're ignoring errors then we can not reliably render the dependency tree fully at all, since there may be information which constrains the tree that was masked by ignoring the error.

**Comment by davystrong** [comment]
Ok, I guess it doesn't make sense. But a more specific error message would still be helpful, I think. Let me know if you want me to test anything.
