### ISSUE TITLE
Make JohnnyDist less verbose

### ISSUE THREAD

**Issue by PhantomLel** [wimglenn/johnnydep#84]
Hi is there any way to make the JohnnyDist class not log anything when checking a package? I am using the `version_installed` and `version_latest` properties to check if my package is fully updated, but it logs a bunch of debugging things that I don't want.

**Comment by wimglenn** [comment]
Hi @PhantomLel 
You can reduce the logging verbosity from default (INFO) by using the verbose flag `-v0`:

```
$ johnnydep --help | grep verbose
                 [--for-python ENV] [--verbose {0,1,2}] [--version]
  --verbose {0,1,2}, -v {0,1,2}
```

Example:

```
$ johnnydep six    
2022-04-10 00:13:54 [info     ] init johnnydist                [johnnydep.lib] dist=six parent=None
name    summary
------  --------------------------------------
six     Python 2 and 3 compatibility utilities

$ johnnydep six -v0
name    summary
------  --------------------------------------
six     Python 2 and 3 compatibility utilities
```

**Comment by PhantomLel** [comment]
Thank you that works
