### ISSUE TITLE
No fields with output format pinned

### ISSUE THREAD

**Issue by muendlein** [wimglenn/johnnydep#91]
I.e. `johnnydep pandas --output-format pinned --fields license` only returns the packages themselves but not the respective fields corresponding to the resolved packages.

**Comment by wimglenn** [comment]
`--output-format pinned` is supposed to generate output in [requirements file format](https://pip.pypa.io/en/stable/reference/requirements-file-format/).  there is no space for a license field in requirements.txt format (although I suppose it could be added as a comment line ...)

**Comment by muendlein** [comment]
@wimglenn To be clear what I desire is resolving the dependencies while also allowing all regular fields. Unless I am overlooking something the pinned format does resolve dependencies and generate the requirements format from there. However I think that the former part would be nice to have as a standalone feature.

**Comment by wimglenn** [comment]
All the output formats are also resolving, except for "human" which renders the tree structure. For example, this will resolve and merge specifiers:

    $ johnnydep boto3 --output-format yaml --fields name version_latest_in_spec license

So I guess I'm not understanding why you need to render extra fields specifically in the "pinned" output format. If pinned output format grows extra fields, it would need to be done in a way which is still acceptable to `pip install --no-deps --requirement <file>`)

**Comment by muendlein** [comment]
I do not need the pinned format itself. I just got confused by the statement listed for the pinned example "Johnnydep can also attempt to resolve the dependency tree". You already provided what I need and that is --fields name version_latest_in_spec.
